# Generated by Django 4.2.16 on 2024-11-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_price_listing_price_per_night_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listingType',
            new_name='listing_type',
        ),
    ]
